#!/usr/bin/env python3
"""
SEO report generator. Pulls data from PostgreSQL and renders
an HTML report using Jinja2 templates.
"""

import argparse
import json
import os
from datetime import date, timedelta

import psycopg2
import psycopg2.extras
from jinja2 import Template


WEEKLY_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SEO Weekly Report — {{ report_date }}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 24px; color: #1a1a1a; }
  h1 { color: #1a1a1a; border-bottom: 3px solid #2563eb; padding-bottom: 12px; }
  h2 { color: #374151; margin-top: 32px; }
  .metric { display: inline-block; background: #f3f4f6; border-radius: 8px; padding: 16px 24px; margin: 8px; text-align: center; min-width: 140px; }
  .metric-value { font-size: 2em; font-weight: 700; color: #2563eb; }
  .metric-label { font-size: 0.85em; color: #6b7280; margin-top: 4px; }
  .positive { color: #059669; }
  .negative { color: #dc2626; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th { background: #2563eb; color: white; padding: 10px 12px; text-align: left; }
  td { padding: 9px 12px; border-bottom: 1px solid #e5e7eb; }
  tr:hover { background: #f9fafb; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 0.8em; font-weight: 600; }
  .badge-high { background: #fee2e2; color: #991b1b; }
  .badge-medium { background: #fef3c7; color: #92400e; }
  .badge-low { background: #d1fae5; color: #065f46; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 0.85em; }
</style>
</head>
<body>
<h1>📈 Weekly SEO Report</h1>
<p style="color: #6b7280;">Week ending {{ report_date }} &nbsp;|&nbsp; Generated by SEO AI Employee</p>

<h2>Executive Summary</h2>
<div>
  <div class="metric">
    <div class="metric-value">{{ summary.clicks }}</div>
    <div class="metric-label">Clicks</div>
    <div class="{% if summary.clicks_change >= 0 %}positive{% else %}negative{% endif %}">
      {% if summary.clicks_change >= 0 %}+{% endif %}{{ summary.clicks_change }}%
    </div>
  </div>
  <div class="metric">
    <div class="metric-value">{{ summary.impressions }}</div>
    <div class="metric-label">Impressions</div>
    <div class="{% if summary.impressions_change >= 0 %}positive{% else %}negative{% endif %}">
      {% if summary.impressions_change >= 0 %}+{% endif %}{{ summary.impressions_change }}%
    </div>
  </div>
  <div class="metric">
    <div class="metric-value">{{ summary.avg_position }}</div>
    <div class="metric-label">Avg Position</div>
  </div>
  <div class="metric">
    <div class="metric-value">{{ summary.articles_published }}</div>
    <div class="metric-label">Articles Published</div>
  </div>
  <div class="metric">
    <div class="metric-value">{{ summary.issues_fixed }}</div>
    <div class="metric-label">Issues Fixed</div>
  </div>
</div>

{% if ranking_gains %}
<h2>Top Ranking Gains</h2>
<table>
  <tr><th>Page</th><th>Keyword</th><th>Previous</th><th>Current</th><th>Change</th></tr>
  {% for r in ranking_gains %}
  <tr>
    <td><a href="{{ r.url }}">{{ r.url|truncate(60) }}</a></td>
    <td>{{ r.keyword }}</td>
    <td>{{ r.prev_position }}</td>
    <td>{{ r.position }}</td>
    <td class="positive">▲ {{ r.change }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

{% if ranking_drops %}
<h2>Ranking Drops to Watch</h2>
<table>
  <tr><th>Page</th><th>Keyword</th><th>Previous</th><th>Current</th><th>Change</th></tr>
  {% for r in ranking_drops %}
  <tr>
    <td><a href="{{ r.url }}">{{ r.url|truncate(60) }}</a></td>
    <td>{{ r.keyword }}</td>
    <td>{{ r.prev_position }}</td>
    <td>{{ r.position }}</td>
    <td class="negative">▼ {{ r.change }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

{% if published_articles %}
<h2>Content Published This Week</h2>
<table>
  <tr><th>Title</th><th>Primary Keyword</th><th>Published</th></tr>
  {% for a in published_articles %}
  <tr>
    <td>{{ a.title }}</td>
    <td>{{ a.primary_keyword }}</td>
    <td>{{ a.published_at }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

{% if priorities %}
<h2>Top Priorities for Next Week</h2>
<ol>
  {% for p in priorities %}
  <li>
    <strong>{{ p.action }}</strong> — {{ p.reason }}
    <span class="badge badge-{{ p.priority }}">{{ p.priority }}</span>
  </li>
  {% endfor %}
</ol>
{% endif %}

<div class="footer">
  Generated by SEO AI Employee on {{ report_date }}.<br>
  Data sources: Google Search Console, DataForSEO, internal database.
</div>
</body>
</html>
"""


def get_db_conn():
    db_url = os.environ.get("DATABASE_URL", "")
    if not db_url:
        raise RuntimeError("DATABASE_URL env var not set")
    return psycopg2.connect(db_url)


def fetch_summary(conn, days: int) -> dict:
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute("""
            SELECT
                COALESCE(SUM(clicks), 0) AS clicks,
                COALESCE(SUM(impressions), 0) AS impressions,
                COALESCE(ROUND(AVG(position)::numeric, 1), 0) AS avg_position
            FROM gsc_data
            WHERE recorded_at >= CURRENT_DATE - INTERVAL '%s days'
        """, (days,))
        current = dict(cur.fetchone() or {})

        cur.execute("""
            SELECT COALESCE(SUM(clicks), 0) AS clicks, COALESCE(SUM(impressions), 0) AS impressions
            FROM gsc_data
            WHERE recorded_at >= CURRENT_DATE - INTERVAL '%s days'
              AND recorded_at < CURRENT_DATE - INTERVAL '%s days'
        """, (days * 2, days))
        prev = dict(cur.fetchone() or {})

        def pct(now, before):
            if not before:
                return 0
            return round((now - before) / before * 100, 1)

        cur.execute("""
            SELECT COUNT(*) AS cnt FROM articles
            WHERE status = 'published' AND published_at >= CURRENT_DATE - INTERVAL '%s days'
        """, (days,))
        articles = (cur.fetchone() or {}).get("cnt", 0)

        cur.execute("""
            SELECT COUNT(*) AS cnt FROM audit_issues
            WHERE status = 'resolved' AND resolved_at >= CURRENT_DATE - INTERVAL '%s days'
        """, (days,))
        issues_fixed = (cur.fetchone() or {}).get("cnt", 0)

    return {
        "clicks": current.get("clicks", 0),
        "impressions": current.get("impressions", 0),
        "avg_position": current.get("avg_position", 0),
        "clicks_change": pct(current.get("clicks", 0), prev.get("clicks", 0)),
        "impressions_change": pct(current.get("impressions", 0), prev.get("impressions", 0)),
        "articles_published": articles,
        "issues_fixed": issues_fixed,
    }


def fetch_ranking_changes(conn, days: int) -> tuple[list, list]:
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute("""
            WITH current_period AS (
                SELECT page AS url, query AS keyword, AVG(position) AS position
                FROM gsc_data
                WHERE recorded_at >= CURRENT_DATE - INTERVAL '%s days'
                GROUP BY page, query
            ),
            prev_period AS (
                SELECT page AS url, query AS keyword, AVG(position) AS position
                FROM gsc_data
                WHERE recorded_at >= CURRENT_DATE - INTERVAL '%s days'
                  AND recorded_at < CURRENT_DATE - INTERVAL '%s days'
                GROUP BY page, query
            )
            SELECT c.url, c.keyword,
                   ROUND(p.position::numeric, 1) AS prev_position,
                   ROUND(c.position::numeric, 1) AS position,
                   ROUND((p.position - c.position)::numeric, 1) AS change
            FROM current_period c
            JOIN prev_period p USING (url, keyword)
            WHERE ABS(p.position - c.position) >= 1
            ORDER BY change DESC
            LIMIT 20
        """, (days, days * 2, days))
        rows = [dict(r) for r in cur.fetchall()]

    gains = [r for r in rows if r["change"] > 0][:10]
    drops = [r for r in rows if r["change"] < 0]
    drops.sort(key=lambda x: x["change"])
    return gains, drops[:10]


def fetch_published_articles(conn, days: int) -> list:
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute("""
            SELECT title, primary_keyword, published_at::date AS published_at
            FROM articles
            WHERE status = 'published' AND published_at >= CURRENT_DATE - INTERVAL '%s days'
            ORDER BY published_at DESC
        """, (days,))
        return [dict(r) for r in cur.fetchall()]


def fetch_priorities(conn, limit: int = 5) -> list:
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute("""
            SELECT action, reason, priority
            FROM seo_priorities
            WHERE completed_at IS NULL
            ORDER BY
                CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
                created_at DESC
            LIMIT %s
        """, (limit,))
        return [dict(r) for r in cur.fetchall()]


def generate_report(period: str, output_path: str):
    days = 7 if period == "weekly" else 30
    conn = get_db_conn()

    try:
        summary = fetch_summary(conn, days)
        gains, drops = fetch_ranking_changes(conn, days)
        articles = fetch_published_articles(conn, days)
        priorities = fetch_priorities(conn)
    finally:
        conn.close()

    html = Template(WEEKLY_TEMPLATE).render(
        report_date=str(date.today()),
        period=period,
        summary=summary,
        ranking_gains=gains,
        ranking_drops=drops,
        published_articles=articles,
        priorities=priorities,
    )

    with open(output_path, "w") as f:
        f.write(html)
    print(f"Report saved: {output_path}")
    return output_path


def main():
    parser = argparse.ArgumentParser(description="SEO Report Generator")
    parser.add_argument("--period", choices=["weekly", "monthly"], default="weekly")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    generate_report(args.period, args.output)


if __name__ == "__main__":
    main()
